//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetCredentialProviderSessionTokenCache {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NuGetCredentialProviderSessionTokenCache.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AADAuthorityNotFound {
            get {
                return ResourceManager.GetString("AADAuthorityNotFound", resourceCulture);
            }
        }
        
        internal static string AADAuthorityOverrideFound {
            get {
                return ResourceManager.GetString("AADAuthorityOverrideFound", resourceCulture);
            }
        }
        
        internal static string AcquireSessionTokenFailed {
            get {
                return ResourceManager.GetString("AcquireSessionTokenFailed", resourceCulture);
            }
        }
        
        internal static string AdalDeviceFlowMessage {
            get {
                return ResourceManager.GetString("AdalDeviceFlowMessage", resourceCulture);
            }
        }
        
        internal static string AdalDeviceFlowRequestedResource {
            get {
                return ResourceManager.GetString("AdalDeviceFlowRequestedResource", resourceCulture);
            }
        }
        
        internal static string AdalFileCacheDisabled {
            get {
                return ResourceManager.GetString("AdalFileCacheDisabled", resourceCulture);
            }
        }
        
        internal static string AdalFileCacheLocation {
            get {
                return ResourceManager.GetString("AdalFileCacheLocation", resourceCulture);
            }
        }
        
        internal static string AdalUsingAuthority {
            get {
                return ResourceManager.GetString("AdalUsingAuthority", resourceCulture);
            }
        }
        
        internal static string BuildTaskEnvVarError {
            get {
                return ResourceManager.GetString("BuildTaskEnvVarError", resourceCulture);
            }
        }
        
        internal static string BuildTaskFailedToAuthenticate {
            get {
                return ResourceManager.GetString("BuildTaskFailedToAuthenticate", resourceCulture);
            }
        }
        
        internal static string BuildTaskMatchedPrefix {
            get {
                return ResourceManager.GetString("BuildTaskMatchedPrefix", resourceCulture);
            }
        }
        
        internal static string BuildTaskNoPrefixMatch {
            get {
                return ResourceManager.GetString("BuildTaskNoPrefixMatch", resourceCulture);
            }
        }
        
        internal static string BuildTaskUriPrefixes {
            get {
                return ResourceManager.GetString("BuildTaskUriPrefixes", resourceCulture);
            }
        }
        
        internal static string CachedSessionTokenNotFound {
            get {
                return ResourceManager.GetString("CachedSessionTokenNotFound", resourceCulture);
            }
        }
        
        internal static string CachingSessionToken {
            get {
                return ResourceManager.GetString("CachingSessionToken", resourceCulture);
            }
        }
        
        internal static string CommandLineArgs {
            get {
                return ResourceManager.GetString("CommandLineArgs", resourceCulture);
            }
        }
        
        internal static string CouldNotParseAADAuthorityOverride {
            get {
                return ResourceManager.GetString("CouldNotParseAADAuthorityOverride", resourceCulture);
            }
        }
        
        internal static string CouldNotParseSessionTimeOverride {
            get {
                return ResourceManager.GetString("CouldNotParseSessionTimeOverride", resourceCulture);
            }
        }
        
        internal static string CreateSessionTokenActivityId {
            get {
                return ResourceManager.GetString("CreateSessionTokenActivityId", resourceCulture);
            }
        }
        
        internal static string CreatingProgressReporter {
            get {
                return ResourceManager.GetString("CreatingProgressReporter", resourceCulture);
            }
        }
        
        internal static string DPAPIUnavailableNonWindows {
            get {
                return ResourceManager.GetString("DPAPIUnavailableNonWindows", resourceCulture);
            }
        }
        
        internal static string FaultedOnMessage {
            get {
                return ResourceManager.GetString("FaultedOnMessage", resourceCulture);
            }
        }
        
        internal static string FoundAADAuthorityFromHeaders {
            get {
                return ResourceManager.GetString("FoundAADAuthorityFromHeaders", resourceCulture);
            }
        }
        
        internal static string FoundCachedSessionToken {
            get {
                return ResourceManager.GetString("FoundCachedSessionToken", resourceCulture);
            }
        }
        
        internal static string FoundHostsInEnvironment {
            get {
                return ResourceManager.GetString("FoundHostsInEnvironment", resourceCulture);
            }
        }
        
        internal static string HandlingAuthRequest {
            get {
                return ResourceManager.GetString("HandlingAuthRequest", resourceCulture);
            }
        }
        
        internal static string HandlingRequest {
            get {
                return ResourceManager.GetString("HandlingRequest", resourceCulture);
            }
        }
        
        internal static string InvalidatingCachedSessionToken {
            get {
                return ResourceManager.GetString("InvalidatingCachedSessionToken", resourceCulture);
            }
        }
        
        internal static string IsRetry {
            get {
                return ResourceManager.GetString("IsRetry", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string PluginTimedOut {
            get {
                return ResourceManager.GetString("PluginTimedOut", resourceCulture);
            }
        }
        
        internal static string Redacted {
            get {
                return ResourceManager.GetString("Redacted", resourceCulture);
            }
        }
        
        internal static string RequestUriNull {
            get {
                return ResourceManager.GetString("RequestUriNull", resourceCulture);
            }
        }
        
        internal static string RunningInPlugin {
            get {
                return ResourceManager.GetString("RunningInPlugin", resourceCulture);
            }
        }
        
        internal static string RunningInStandAlone {
            get {
                return ResourceManager.GetString("RunningInStandAlone", resourceCulture);
            }
        }
        
        internal static string SendingResponse {
            get {
                return ResourceManager.GetString("SendingResponse", resourceCulture);
            }
        }
        
        internal static string SessionTokenCacheDisabled {
            get {
                return ResourceManager.GetString("SessionTokenCacheDisabled", resourceCulture);
            }
        }
        
        internal static string SessionTokenCacheLocation {
            get {
                return ResourceManager.GetString("SessionTokenCacheLocation", resourceCulture);
            }
        }
        
        internal static string SkippingCredentialProvider {
            get {
                return ResourceManager.GetString("SkippingCredentialProvider", resourceCulture);
            }
        }
        
        internal static string SPSAuthEndpointException {
            get {
                return ResourceManager.GetString("SPSAuthEndpointException", resourceCulture);
            }
        }
        
        internal static string SPSAuthEndpointNotFound {
            get {
                return ResourceManager.GetString("SPSAuthEndpointNotFound", resourceCulture);
            }
        }
        
        internal static string Uri {
            get {
                return ResourceManager.GetString("Uri", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string VSTSCreateSessionException {
            get {
                return ResourceManager.GetString("VSTSCreateSessionException", resourceCulture);
            }
        }
        
        internal static string VSTSCredentialsNotFound {
            get {
                return ResourceManager.GetString("VSTSCredentialsNotFound", resourceCulture);
            }
        }
        
        internal static string VSTSSessionTokenCreated {
            get {
                return ResourceManager.GetString("VSTSSessionTokenCreated", resourceCulture);
            }
        }
        
        internal static string VSTSSessionTokenValidity {
            get {
                return ResourceManager.GetString("VSTSSessionTokenValidity", resourceCulture);
            }
        }
        
        internal static string EnvironmentVariableHelp {
            get {
                return ResourceManager.GetString("EnvironmentVariableHelp", resourceCulture);
            }
        }
        
        internal static string CredentialParseFailure {
            get {
                return ResourceManager.GetString("CredentialParseFailure", resourceCulture);
            }
        }
        
        internal static string EndpointCredentialCheck {
            get {
                return ResourceManager.GetString("EndpointCredentialCheck", resourceCulture);
            }
        }
        
        internal static string EndpointParseFailure {
            get {
                return ResourceManager.GetString("EndpointParseFailure", resourceCulture);
            }
        }
        
        internal static string NoEndpointMatch {
            get {
                return ResourceManager.GetString("NoEndpointMatch", resourceCulture);
            }
        }
        
        internal static string NoEndpointsFound {
            get {
                return ResourceManager.GetString("NoEndpointsFound", resourceCulture);
            }
        }
        
        internal static string ParsingJson {
            get {
                return ResourceManager.GetString("ParsingJson", resourceCulture);
            }
        }
        
        internal static string VstsBuildTaskExternalCredentialCredentialProviderError {
            get {
                return ResourceManager.GetString("VstsBuildTaskExternalCredentialCredentialProviderError", resourceCulture);
            }
        }
        
        internal static string BuildTaskEndpointEnvVarError {
            get {
                return ResourceManager.GetString("BuildTaskEndpointEnvVarError", resourceCulture);
            }
        }
        
        internal static string AcquireBearerTokenSuccess {
            get {
                return ResourceManager.GetString("AcquireBearerTokenSuccess", resourceCulture);
            }
        }
        
        internal static string AttemptingToAcquireBearerTokenUsingProvider {
            get {
                return ResourceManager.GetString("AttemptingToAcquireBearerTokenUsingProvider", resourceCulture);
            }
        }
        
        internal static string BearerTokenProviderException {
            get {
                return ResourceManager.GetString("BearerTokenProviderException", resourceCulture);
            }
        }
        
        internal static string BearerTokenProviderReturnedNull {
            get {
                return ResourceManager.GetString("BearerTokenProviderReturnedNull", resourceCulture);
            }
        }
        
        internal static string ExchangingBearerTokenForSessionToken {
            get {
                return ResourceManager.GetString("ExchangingBearerTokenForSessionToken", resourceCulture);
            }
        }
        
        internal static string NotRunningBearerTokenProvider {
            get {
                return ResourceManager.GetString("NotRunningBearerTokenProvider", resourceCulture);
            }
        }
        
        internal static string DeviceFlowTimedOut {
            get {
                return ResourceManager.GetString("DeviceFlowTimedOut", resourceCulture);
            }
        }
        
        internal static string CouldNotParseDeviceFlowTimeoutOverride {
            get {
                return ResourceManager.GetString("CouldNotParseDeviceFlowTimeoutOverride", resourceCulture);
            }
        }
        
        internal static string BuildTaskCredProviderIsUsedError {
            get {
                return ResourceManager.GetString("BuildTaskCredProviderIsUsedError", resourceCulture);
            }
        }
        
        internal static string BuildTaskEndpointNoMatchingUrl {
            get {
                return ResourceManager.GetString("BuildTaskEndpointNoMatchingUrl", resourceCulture);
            }
        }
        
        internal static string BuildTaskEndpointMatchingUrlFound {
            get {
                return ResourceManager.GetString("BuildTaskEndpointMatchingUrlFound", resourceCulture);
            }
        }
        
        internal static string CancelMessage {
            get {
                return ResourceManager.GetString("CancelMessage", resourceCulture);
            }
        }
        
        internal static string ResponseHandlerException {
            get {
                return ResourceManager.GetString("ResponseHandlerException", resourceCulture);
            }
        }
        
        internal static string CacheException {
            get {
                return ResourceManager.GetString("CacheException", resourceCulture);
            }
        }
        
        internal static string BuildTaskNoMatchingPrefixes {
            get {
                return ResourceManager.GetString("BuildTaskNoMatchingPrefixes", resourceCulture);
            }
        }
        
        internal static string RequestHandlerCancelingExceptionMessage {
            get {
                return ResourceManager.GetString("RequestHandlerCancelingExceptionMessage", resourceCulture);
            }
        }
        
        internal static string ShuttingDown {
            get {
                return ResourceManager.GetString("ShuttingDown", resourceCulture);
            }
        }
        
        internal static string StartRequestHandlerStopwatch {
            get {
                return ResourceManager.GetString("StartRequestHandlerStopwatch", resourceCulture);
            }
        }
        
        internal static string TimeElapsedAfterSendingResponse {
            get {
                return ResourceManager.GetString("TimeElapsedAfterSendingResponse", resourceCulture);
            }
        }
        
        internal static string SessionTokenCacheMutexFail {
            get {
                return ResourceManager.GetString("SessionTokenCacheMutexFail", resourceCulture);
            }
        }
        
        internal static string SessionTokenCacheMutexMiss {
            get {
                return ResourceManager.GetString("SessionTokenCacheMutexMiss", resourceCulture);
            }
        }
    }
}
